name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lintRelease:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v2
      - name: Access secret
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        run: echo ACCESS_KEY=$ACCESS_KEY > ./local.properties
      - name: Access google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > ./app/google-services.json
      - name: Build
        run: ./gradlew lintRelease
  test:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v2
      - name: Access secret
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        run: echo ACCESS_KEY=$ACCESS_KEY > ./local.properties
      - name: Access google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > ./app/google-services.json
      - name: Test
        run: ./gradlew testDebugUnitTest
  detekt:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v2
      - name: Access secret
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        run: echo ACCESS_KEY=$ACCESS_KEY > ./local.properties
      - name: Access google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > ./app/google-services.json
      - name: Run detekt
        run: ./gradlew detekt
